Replace space indentation with tabs, and rewrite multiline output to use here docus

diff --git a/bin/ide b/bin/ide
--- a/bin/ide
+++ b/bin/ide
@@ -2,84 +2,81 @@
 
 set -e
 
-HELP_OUTPUT=\
-"Usage: $(basename "$0") [path]
-
-Arguments
-    path (optional) - Path to project root directory."
-
-UNDEFINED_EDITOR_ERROR_OUTPUT=\
-"No editor was configured. Specify the editor you would like to use by setting the \$EDITOR variable.
-
-For example, in order to use Vim as your editor, add following line to your ~/.zshrc:
-export EDITOR=vim"
-
-TMUX_NOT_INSTALLED_ERROR_OUTPUT=\
-"Did not find tmux, which is a required dependency for $(basename "$0") command.
-
-You can install tmux e.g. via homebrew by running
-brew install tmux"
-
 is_git_repo() {
-    local DIR="$1"
-    test "$(git -C "$DIR" rev-parse --is-inside-work-tree 2>/dev/null)" = "true"
+	local DIR="$1"
+	test "$(git -C "$DIR" rev-parse --is-inside-work-tree 2>/dev/null)" = "true"
 }
 
 # Validate user input
 if [[ $# -gt 1 ]]; then
-    echo "Too many arguments. See $(basename "$0") --help.">&2
-    exit 1
+	echo "Too many arguments. See $(basename "$0") --help.">&2
+	exit 1
 elif [[ "$1" == "--help" || "$1" == "-h"  ]]; then
-    echo "$HELP_OUTPUT"
-    exit 0
+	cat <<- END
+		Usage: $(basename "$0") [path]
+
+		Arguments
+			path (optional) - Path to project root directory.
+	END
+	exit 0
 elif [[ $# -eq 1 && ! -e "$1" ]]; then
-    echo "Received an invalid path: $1">&2
-    exit 1
+	echo "Received an invalid path: $1">&2
+	exit 1
 fi
 
 if [[ $# -eq 0 ]]; then
-    SELECTED_PATH=$PWD
+	SELECTED_PATH=$PWD
 else
-    SELECTED_PATH=$(realpath "$1")
+	SELECTED_PATH=$(realpath "$1")
 fi
 
 if is_git_repo "$SELECTED_PATH"; then
-    WORKING_DIRECTORY=$(git -C "$SELECTED_PATH" rev-parse --show-toplevel)
+	WORKING_DIRECTORY=$(git -C "$SELECTED_PATH" rev-parse --show-toplevel)
 elif [[ -d "$SELECTED_PATH" ]]; then
-    WORKING_DIRECTORY="$SELECTED_PATH"
+	WORKING_DIRECTORY="$SELECTED_PATH"
 else
-    WORKING_DIRECTORY=$(dirname "$SELECTED_PATH")
+	WORKING_DIRECTORY=$(dirname "$SELECTED_PATH")
 fi
 
 SELECTED_PATH_HASH=$(sha256 <<< "$SELECTED_PATH")
 SESSION="$(basename "$SELECTED_PATH"  | tr . _)-${SELECTED_PATH_HASH:0:4}"
 
 if [ ! -z "$VISUAL" ]; then
-    IDE_EDITOR="$VISUAL"
+	IDE_EDITOR="$VISUAL"
 elif [ ! -z "$EDITOR" ]; then
-    IDE_EDITOR="$EDITOR"
+	IDE_EDITOR="$EDITOR"
 else
-    echo "$UNDEFINED_EDITOR_ERROR_OUTPUT" >&2
-    exit 1
+	cat <<- END >&2
+		No editor was configured. Specify the editor you would like to use by setting the \$EDITOR variable.
+
+		For example, in order to use Vim as your editor, add following line to your ~/.zshrc:
+		export EDITOR=vim"
+	END
+	exit 1
 fi
 
 if ! command -v tmux > /dev/null 2>&1; then
-    echo "$TMUX_NOT_INSTALLED_ERROR_OUTPUT" >&2
-    exit 1
+	cat <<- END >&2
+		Did not find tmux, which is a required dependency for $(basename "$0") command.
+
+		You can install tmux e.g. via homebrew by running
+		brew install tmux
+	END
+	exit 1
 fi
 
 if ! tmux has-session -t="$SESSION" 2> /dev/null; then
-    tmux new-session -ds "$SESSION" -c "$WORKING_DIRECTORY" "$IDE_EDITOR" "$SELECTED_PATH"
+	tmux new-session -ds "$SESSION" -c "$WORKING_DIRECTORY" "$IDE_EDITOR" "$SELECTED_PATH"
 
-    # Start lazygit if installed and in git repo.
-    if is_git_repo "$SELECTED_PATH" && command -v lazygit > /dev/null 2>&1; then
-        tmux new-window -d -t "$SESSION" -c "$WORKING_DIRECTORY" lazygit
-    fi
+	# Start lazygit if installed and in git repo.
+	if is_git_repo "$SELECTED_PATH" && command -v lazygit > /dev/null 2>&1; then
+		tmux new-window -d -t "$SESSION" -c "$WORKING_DIRECTORY" lazygit
+	fi
 fi
 
 if [[ -z $TMUX ]]; then
-    tmux attach -t "$SESSION"
+	tmux attach -t "$SESSION"
 else
-    tmux switch-client -t "$SESSION"
+	tmux switch-client -t "$SESSION"
 fi
 
